/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cet001.icaro.vista;

/**
 *
 * @author ponsa
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Princpial
     */
    public PrincipalView() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pNotificaciones = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        choferes = new javax.swing.JMenu();
        consultarChoferes = new javax.swing.JMenuItem();
        menuComi = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuAgregarOperador = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        agreCliente = new javax.swing.JMenuItem();
        jMenuMovSaldo = new javax.swing.JMenuItem();
        menuVeh = new javax.swing.JMenu();
        menuV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Vehiculos Disponibles:");

        jLabel2.setText("Viajes En Curso:");

        pNotificaciones.setEditable(false);
        pNotificaciones.setForeground(new java.awt.Color(255, 51, 0));
        jScrollPane1.setViewportView(pNotificaciones);

        jScrollPane4.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/viaje.png"))); // NOI18N

        jMenuItem1.setText("Nuevo Viaje...");
        jMenuItem1.setActionCommand("nviaje");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem8.setText("Cobrar Viaje...");
        jMenu2.add(jMenuItem8);

        jMenuItem7.setText("Cancelar Viaje...");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        choferes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chofer.png"))); // NOI18N
        choferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choferesActionPerformed(evt);
            }
        });

        consultarChoferes.setText("Administracion Choferes");
        consultarChoferes.setActionCommand("admChoferes");
        consultarChoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarChoferesActionPerformed(evt);
            }
        });
        choferes.add(consultarChoferes);

        menuComi.setText("Comisiones...");
        menuComi.setActionCommand("menuComi");
        choferes.add(menuComi);

        jMenuBar1.add(choferes);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/operador.png"))); // NOI18N

        menuAgregarOperador.setText("Agregar Operador...");
        menuAgregarOperador.setActionCommand("nOpe");
        menuAgregarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarOperadorActionPerformed(evt);
            }
        });
        jMenu1.add(menuAgregarOperador);

        jMenuBar1.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pasajero2.png"))); // NOI18N

        agreCliente.setText("Administar Clientes...");
        agreCliente.setActionCommand("agreCliente");
        agreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreClienteActionPerformed(evt);
            }
        });
        jMenu4.add(agreCliente);

        jMenuMovSaldo.setText("Movimientos de Saldo...");
        jMenuMovSaldo.setActionCommand("movSaldo");
        jMenuMovSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMovSaldoActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuMovSaldo);

        jMenuBar1.add(jMenu4);

        menuVeh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vehiculo.png"))); // NOI18N
        menuVeh.setActionCommand("menuVeh");

        menuV.setText("Editar Vehiculos...");
        menuV.setActionCommand("menuVeh");
        menuV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVActionPerformed(evt);
            }
        });
        menuVeh.add(menuV);

        jMenuBar1.add(menuVeh);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //Agregar viaje 
  

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void choferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choferesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choferesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();    }//GEN-LAST:event_jButton1ActionPerformed

    private void agreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agreClienteActionPerformed

    private void menuAgregarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarOperadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAgregarOperadorActionPerformed

    private void menuVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuVActionPerformed

    private void consultarChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarChoferesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarChoferesActionPerformed

    private void jMenuMovSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMovSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMovSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem agreCliente;
    public javax.swing.JMenu choferes;
    public javax.swing.JMenuItem consultarChoferes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JList<String> jList1;
    public javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    public javax.swing.JMenuItem jMenuMovSaldo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JMenuItem menuAgregarOperador;
    public javax.swing.JMenuItem menuComi;
    public javax.swing.JMenuItem menuV;
    public javax.swing.JMenu menuVeh;
    public javax.swing.JTextPane pNotificaciones;
    // End of variables declaration//GEN-END:variables
}
